### ISSUE TITLE
Is this library or a tool?

### ISSUE THREAD

**Issue by kgrvamsi** [data-story-org/data-story#232]
Hello @ajthinking 

Love this tool on how it works and would like to know if this can be used as library in an existing react project.

**Comment by ajthinking** [comment]
Hi @kgrvamsi, thanks for reaching out.
While that is the goal, it is not quite ready to be used as a lib just yet. At the moment it needs its own tag `<div id="app">` and the js-bundle to render to that tag. But I think we should be able to setup exports of a `<DataStory>` react component, which would make it possible to use inside existing apps shortly 👍

**Comment by ajthinking** [comment]
To some degree, fixed in #256. Closing for now
